### ISSUE TITLE
Validation Abstractions

### ISSUE THREAD

**Issue by JasonMWebb** [RCommon-Team/RCommon#50]
Need to either create validation abstractions or promote Fluent Validation library to first class citizen. There are currently two conflicting sets of validation classes in play 1) Original NCommon/native validations 2) [Fluent Validations.](https://fluentvalidation.net/) Fluent Validations obviously has a lot of support, while the native validations support more generic validations via specifications supported by RCommon. 

Look into:

- See if we can implement specification based validation in Fluent validations and tie that to a generic interface/abstraction
- Decide if carrying around native validations is worth it assuming we'll have to create some consistency between libraries.

**Comment by jasonmwebb-lv** [comment]
Implemented as part of 2.0.0.878
